print("\n\nWhat's ya name bub?")
var1 = input()
print("Hey I gotta uncle named", var1, "\nSo what's ya last name?")
var2 = input()
print("Well its nice t' meet ya", var1, var2, "\nYou gotta favorite color or somethin'?")
var3 = input()
print("Ugh. Yous one a them", var3, "likin' kooks. \nIm more of a Pantone 448 C kinda guy. \nWhat about food then? You gotta favorite food?")
var4 = input()
print("Ah.", var4, "Good choice. \nWell I betta get goin'", var1, "See ya around.\n\n")